[directories]
posts = "content/posts"
pages = "content/pages"
templates = "templates"
dist = "dist"

[author]
name = "Jon"

[files]
extension = ".html"

[site]
title = "My amazing site"
language = "en-gb"
